### ISSUE TITLE
Random Forest Performance Calculation Error

### ISSUE THREAD

**Issue by Shelomoh1** [apolat2018/LSAT#6]
@apolat2018 Random Forest model is able to train but an error pops up during the performance calculation. The error is as follows:

Starting Training
Saving Prediction Data as rf.csv
Analysis finished
Creating SUSCEPTIBILITY Map and Calculating ROC 
Susceptibility Map was created in D:\LSM\Results\RF folder as rf_sus raster file
Failed script RF...

Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.4\Scripts\LSAT-master\randomforest.py", line 145, in <module>
    trn.save(train_exp)
RuntimeError: ERROR 000871: D:\LSM\4_ArcGIS\train.tif: Unable to delete the output ????????????????????.

Failed to execute (RF).
Failed at Wed Jun 15 01:22:31 2022 (Elapsed Time: 6 minutes 30 seconds)

**Comment by apolat2018** [comment]
The solution of Esri web page is as below:
Error Message
"000871 : <value>: Unable to delete the output <value>."
Cause
A dataset with the same name as that specified for the output already exists, and it could not be deleted during execution.


Please check the save folder. I think the file "train.tif" already exists. Try to delete all files or select an empty folder.

Thanks.

**Comment by Shelomoh1** [comment]
I figured it out. I had opened the file "train.tif" in a GIS environment which resulted in this error. Closing the file solved the problem.

**Comment by Shelomoh1** [comment]
@apolat2018 Thank you for your prompt response. I want to be able to print the confusion matrix and save the ROC Curve plotting columns to .xlsx. Can you please help me since I am new to python coding?
